name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create API Directory
        run: |
          mkdir -p _site/api
          cp data/*.json _site/api/
          # 创建API文档页面
          cat > _site/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>CCB API Documentation</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
              .endpoint { background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 10px 0; }
              code { background: #e0e0e0; padding: 2px 5px; border-radius: 3px; }
            </style>
          </head>
          <body>
            <h1>CCB API Documentation</h1>
            <div class="endpoint">
              <h2>Get Region List</h2>
              <p>Returns the list of available regions.</p>
              <code>GET /api/region.json</code>
            </div>
            <div class="endpoint">
              <h2>Get CDN Data</h2>
              <p>Returns the CDN data for all regions.</p>
              <code>GET /api/cdn.json</code>
            </div>
            <div class="endpoint">
              <h2>Get Service Info</h2>
              <p>Returns service information including last update time.</p>
              <code>GET /api/info.json</code>
            </div>
          </body>
          </html>
          EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4